from .core.config import (
    BASE_DIR,
    DATABASE_URL,
    DATA_DIR,
    LOCAL_AI_MODEL,
    LOCAL_AI_PROVIDER,
    OLLAMA_HOST,
    NOTIFICATION_PROVIDER,
    NOTIFICATION_TOKEN,
    NOTIFICATION_USER_KEY,
)
